website/models.py
import abc
from . import db
from flask_login import UserMixin
from datetime import datetime
from sqlalchemy.sql import func
from dataclasses import dataclass



class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    username = db.Column(db.String(150), unique=True)
    name = db.Column(db.String(150))
    password = db.Column(db.String(150))    
    is_active = db.Column(db.Boolean, nullable=False, default=False)
    date_created = db.Column(db.DateTime, default=db.func.current_timestamp())
    date_updated = db.Column(db.DateTime, default=db.func.current_timestamp(), onupdate=db.func.current_timestamp())

    def __str__(self) -> str:
        return self.username

    def __repr__(self):
       return f"<id={self.id}, username={self.username}>"
    
    def user_variables(self):

        user_details = {
            'Id:': ['id', self.id],
            'Username:': ['username', self.username],
            'Name:': ['name', self.name],
            'Email:': ['email', self.email],
            'Account Status': ['is_active', self.is_active],
             }
        return user_details
   
    def disable(self):
        self.is_active = False       
    
    def enable(self):
        self.is_active = True


class UserRepository(User):
    def init(self, session):        
        self._session = session

    def get(self, id):
        # user = User.query.filter_by(id=id).first()
        user = User.query.get_or_404(id)
        return user

    def get_all():
        return User.query.all()
    
    def get_by_name(self, name):
        return User.query.filter_by(name=name)

"""
Cum ar arata flow-ul de a face enable la un user de exemplu:
a. utilizatorul apasa butonul in UI si se face call la
   server (again, JS sau refresh - don't care)

b. Flask vede request-ul si creaza o comanda EnableSupplier. O comanda nu este decat un dataclass,
   ex: class EnableSupplier: email: str

c. Aceasta comanda este transmisa catre un MessageBus
   care face legatura cu un handler d. Se apeleaza handler-ul (EnableSupplierHandler - care este de fapt o functie) care,
   folosind repo-ul, gaseste user-ul e. Odata gasit user-ul se apeleaza metoda enable

"""
@dataclass
class EnableSupplier():
    id: int
    email: str
    is_active: bool    


website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager

db = SQLAlchemy()
DB_NAME = "database.db"


def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = "[hNm,9!9x6tqtQ.(&V~Int>;eUP84P"
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
    db.init_app(app)

    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix="/")
    app.register_blueprint(auth, url_prefix="/")

    from .models import User

    create_database(app)

    login_manager = LoginManager()
    login_manager.login_view = "auth.login"
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))

    return app


def create_database(app):
    if not path.exists("website/" + DB_NAME):
        db.create_all(app=app)
        print("Database created!")

website/auth.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from . import db
from .models import User
from flask_login import login_user, logout_user, login_required, current_user
from werkzeug.security import generate_password_hash, check_password_hash

auth = Blueprint("auth", __name__)


@auth.route("/login", methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get("email")
        password = request.form.get("password")

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                if user.is_active == False:
                   flash("This account is disabled.", category='error')
                   return render_template("login.html", user=current_user)
                else:
                    flash("Logged in!", category='success')
                    login_user(user, remember=True)
                    return redirect(url_for('views.home'))
            else:
                flash('Password is incorrect.', category='error')
        else:
            flash('Email does not exist.', category='error')

    return render_template("login.html", user=current_user)


@auth.route("/sign-up", methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        email = request.form.get("email")
        username = request.form.get("username")
        name = request.form.get("name")
        password1 = request.form.get("password1")
        password2 = request.form.get("password2")
        is_active = False

        email_exists = User.query.filter_by(email=email).first()
        username_exists = User.query.filter_by(username=username).first()

        if email_exists:
            flash('Email is already in use.', category='error')
        elif username_exists:
            flash('Username is already in use.', category='error')
        elif password1 != password2:
            flash('Password don\'t match!', category='error')
        elif len(username) < 2:
            flash('Username is too short.', category='error')
        elif len(password1) < 6:
            flash('Password is too short.', category='error')
        elif len(email) < 4:
            flash("Email is invalid.", category='error')
        else:
            new_user = User(email=email, username=username, name=name, password=generate_password_hash(
                password1, method='sha256'), is_active=is_active)
            db.session.add(new_user)
            db.session.commit()
            # login_user(new_user, remember=True)
            flash('User created!')
            return redirect(url_for('views.users'))

    return render_template("signup.html", user=current_user)


@auth.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("views.home"))

website/views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import login_required, current_user
from .models import User, UserRepository, EnableSupplier
from . import db

views = Blueprint("views", __name__)

@views.route("/")
@views.route("/home")
@login_required
def home():    
    return render_template("home.html", user=current_user)


@views.route("/users")
@login_required
def users():
    # users = User.query.all()
    users = UserRepository.get_all()
    return render_template("users.html", user=current_user, users=users)


@views.route("/delete-user/<id>", methods=['GET', 'POST'])
@login_required
def delete_user(id, action=None):
    delete_user = UserRepository()
    user = delete_user.get(id)
    if not user:
        
        flash("User does not exist!", category='error')
        
    else:        
        if request.method == "POST":                
            db.session.delete(user)
            db.session.commit()
            flash('User deleted.', category='success')
            return redirect(url_for('views.users'))
        return render_template("delete_user.html", user=current_user, users=user, id=id)

    return redirect(url_for('views.users'))


@views.route("/edit-user/<id>", methods=['GET', 'POST'])
@login_required
def edit_user(id):
    user = UserRepository()
    edit_user = user.get(id)        
    user_details = edit_user.user_variables()        
    if request.method == 'POST': 
        updated_values_dict = request.form.to_dict()
        checkbox = request.form.get("update_is_active")
        for k, v in updated_values_dict.items():                        
            if k == 'update_id':
                edit_user.id = v.strip()
            if k == 'update_username':
                edit_user.username = v.strip()
            if k == 'update_name':
                edit_user.name = v.strip()
            if k == 'update_email':
                edit_user.email = v.strip()                                 
            if checkbox is None:                
                edit_user.disable()                
            else:
                # edit_user.enable()
                EnableSupplier.is_active = True

        db.session.commit()        
        return redirect(url_for('views.users'))
    return render_template('edit_user.html', user=current_user, user_details=user_details)



website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">            
    <link rel="shortcut icon" href="{{ url_for('static', filename='images/favicon.ico') }}">       
   
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">    
    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/components/badge/">
    <link href="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/font-awesome.min.css') }}">
    <title>Flask TDD - {% block title %}{% endblock %}</title>
</head>
<body>
    {% block nav %}{% endblock %}

    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                {% if category == 'error' %}
                    <div class="alert alert-danger alter-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                    </div>
                {% else %}
                    <div class="alert alert-success alter-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                    </div>
                {% endif %}
            {% endfor %}
        {% endif %}
    {% endwith %}

    <div class="container mt-3">
        {% block content %}{% endblock %}
    </div>
  
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj"
        crossorigin="anonymous"></script>   
    
    <script>
        function goBack() {
        window.history.back();
        }
    </script>

</body>
</html>

website/templates/delete_user.html
{% extends "base.html" %}
{% block title %}Delete User{% endblock %}
{% include 'nav.html' %}
{% block content %}

<form id="form" action="{{ url_for('views.delete_user', id=users.id) }}" method="POST">
    <h3 align="center">Delete, {{users.username}} ?</h3>
    <br/>
    <div class="form-group row">                           
        <div align="center">
            <button class="btn btn-danger" type="submit", action="delete">Delete</button>            
            <input class="btn btn-primary" type="button" value="Cancel" onclick="history.back()">
        </div>        
    </div>
</form>
{% endblock %}

website/templates/edit_user copy.html
{% extends "base.html" %}
{% block title %}Edit User{% endblock %}
{% include 'nav.html' %}
{% block content %}
<form method="POST">
    <h3 align="center">Update</h3>
    <div class="form-group row">
    {% for key in user_details.keys() %}       
            <div class="col-sm-10">               
                    <label for="username" class="col-sm-2 col-form-label">{{ key }}</label>
                    <input class="form-control" id="update_field" name="update_{{user_details[key][0]}}" value="{{user_details[key][1]}}"
                        placeholder="Type to update {{ key }}">
                        
            </div>        
        {% endfor %}
   
        <div align="center">
            <button class="btn btn-primary" type="submit">Update</button>
        </div>
        
    
    </div>
</form>
{% endblock %}

website/templates/edit_user.html
{% extends "base.html" %}
{% block title %}Edit User{% endblock %}
{% include 'nav.html' %}
{% block content %}
<form method="POST">
    <h3 align="center">Update</h3>
    <div class="form-group row">
                   
    {% for key in user_details.keys() %}       
        <div class="col-sm-10 mb-3">
                {% if key == "Account Status" %}
                    {% if user_details[key][1] == True %}
                        <div class="form-check">                             
                            <input class="form-check-input" type="checkbox" value="{{user_details[key][1]}}" id="update_field" name="update_is_active" checked>    
                            <label for="username" class="col-sm-2 col-form-label">{{key}}</label>                                                       
                        </div> 
                    {% else %}
                        <div class="form-check">                             
                            <input class="form-check-input" type="checkbox" value="{{user_details[key][1]}}" id="update_field" name="update_is_active">    
                            <label for="username" class="col-sm-2 col-form-label">{{key}}</label>                                                       
                        </div> 
                    {% endif %}
                {% else %}
                    <label for="username" class="col-sm-2 col-form-label">{{ key }}</label>
                    <input class="form-control" id="update_field" name="update_{{user_details[key][0]}}" value="{{user_details[key][1]}}"
                        placeholder="Type to update {{ key }}">
                {% endif %}
                    
                        
            </div>      
        {% endfor %}                     
            
        <div align="center">
            <button class="btn btn-primary" type="submit">Update</button>
        </div>
        
    </div>
</form>
{% endblock %}

website/templates/home.html
{% extends 'base.html' %}
{% block title %}Home{% endblock %}
{% block nav %}{% include 'nav.html' %}{% endblock %}

{% block content %}

Hello, {{user}}!

{% endblock %}

website/templates/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}
{% include 'nav.html' %}
{% block content%}
<div class="container">
    <div class="row">
        <div class="col-sm"></div>
        <div class="col-sm">
            <!-- <div class="navbar-brand mb-3" align="center">
                <img src="https://www.pentalog.com/wp-content/themes/penta2018/assets/img/fav/apple-icon-57x57.png" width="30"
                    height="30" class="d-inline-block align-top" alt="" loading="lazy">
                <strong>TDD FlaskUsers</strong>
            </div> -->
            <form method="POST">
                <h4 align="center">Login</h4>
                <div class="form-group">
                    <label for="email">Email Address</label>
                    <input type="text" id="email" name="email" class="form-control" placeholder="Enter Email" />
                    <label for="password">Password</label>
                    <input type="password" id="password" name="password" class="form-control" placeholder="Enter Password" />
                    <br />
                    <div align="center">
                        <button class="btn btn-primary" type="submit">Login</button>
                    </div>
                </div>
            </form>
        </div>
        <div class="col-sm"></div>
    </div>
</div>
{% endblock %}

website/templates/nav.html
 <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
     <a class="navbar-brand" href="#">
        <img src="https://www.pentalog.com/wp-content/themes/penta2018/assets/img/fav/apple-icon-57x57.png" width="30" height="30" class="d-inline-block align-top" alt=""
            loading="lazy">
        <strong>TDD FlaskUsers</strong>
    </a>
      <div class="container-fluid">
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbar"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar">
          <div class="navbar-nav">            
            {% if user.is_authenticated %}
              <a class="nav-item nav-link" href="/">Home</a>
              <a class="nav-item nav-link" href="/users">Users</a>
              <a class="nav-item nav-link" href="/sign-up">Add user</a>
              <a class="nav-item nav-link" href="/logout">Logout, <i>{{user.username}}</i></a>
            {% else %}
              <a class="nav-item nav-link" href="/login">Login</a>
              <a class="nav-item nav-link" href="/sign-up">Sign Up</a>
            {% endif %}
          </div>
        </div>
      </div>
    </nav>

website/templates/signup.html
{% extends "base.html" %}
{% block title %}Sign Up{% endblock %}
{% include 'nav.html' %}
{% block content %}
<form method="POST">
    <h3 align="center">Sign Up</h3>
    <div class="form-group">
        <label for="username">Username</label>
        <input type="text" id="username" name="username" class="form-control" placeholder="Enter Username" />
        <label for="name">Name</label>
        <input type="text" id="username" name="name" class="form-control" placeholder="Name" />
        <label for="email">Email Address</label>
        <input type="text" id="email" name="email" class="form-control" placeholder="Enter Email" />
        <label for="password1">Password</label>
        <input type="password" id="password1" name="password1" class="form-control" placeholder="Enter Password" />
        <label for="password2">Password Again</label>
        <input type="password" id="password2" name="password2" class="form-control"
            placeholder="Enter Password Again" />
        <br />
        <div align="center">
            <button class="btn btn-primary" type="submit">Sign Up</button>
        </div>
    </div>
</form>
{% endblock %}

website/templates/users.html
{% extends 'base.html' %}
{% block title %}Users{% endblock %}
{% block nav %}{% include 'nav.html' %}{% endblock %}
{% block content %}

<h1>Users</h1>    
    <table class="table table-striped table-responsive">
        <thead>
            <tr>
                <th scope="col">#</th>          
                <th scope="col">Username</th>
                <th scope="col">Name</th>
                <th scope="col">E-mail</th>
                <th scope="col">Date Created</th>
                <th scope="col">Date Updated</th>
                <th scope="col">Account Status</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            {% for item in users %}
            <tr>
                <th scope="row">{{item.id}}</th>
                <td>{{item.username}}</td>
                <td>{{item.name}}</td>
                <td>{{item.email}}</td>
                <td>{{item.date_created}}</td>
                <td>{{item.date_updated}}</td>
                <td align="center hide-xs">
                    {% if item.is_active == False %}                    
                        <span class="badge alert-danger">Inactive</span>                                            
                    {% else %}                    
                        <span class="badge alert-success">Active</span>
                    {% endif %}
                </td>
                <td align="center hide-xs">
                    <a href="/edit-user/{{item.id}}" class="btn btn-primary btn-sm"><i class="fa fa-pencil fa-1"></i></a>
                    <a href="/delete-user/{{item.id}}" class="btn btn-danger btn-sm"><i class="fa fa-trash fa-1"></i></a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

{% endblock %}